[workspace]
resolver = "2"

members = ["core", "entrypoint"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
hyper = "1.5.1"
hyper-util = "0.1.0"
http-body-util = "0.1.0"
tokio = "1.39.0"

tokio-rustls = "0.26.0"
rustls-pemfile = "2.0.0"

anyhow = "1.0.90"

log = "0.4.20"
env_logger = "0.11.0"
